#!/bin/bash

echo "ROOT_DIR--:${ROOT_DIR}"
Build_DIR=${ROOT_DIR}/Build/
EmulatorX64_DIR=${Build_DIR}/EmulatorX64/
EmulatorX64_DEBUG_XCODE5_DIR=${EmulatorX64_DIR}/DEBUG_XCODE5/
EmulatorX64_DEBUG_XCODE5_X64_DIR=${EmulatorX64_DEBUG_XCODE5_DIR}/X64/
EmulatorX64_DEBUG_XCODE5_FV_DIR=${EmulatorX64_DEBUG_XCODE5_DIR}/FV/


OvmfX64_DIR=${Build_DIR}/OvmfX64/
OvmfX64_DEBUG_XCODE5_DIR=${OvmfX64_DIR}/DEBUG_XCODE5/
OvmfX64_DEBUG_XCODE5_X64_DIR=${OvmfX64_DEBUG_XCODE5_DIR}/X64/
OvmfX64_DEBUG_XCODE5_FV_DIR=${OvmfX64_DEBUG_XCODE5_DIR}/FV/


